"use client";

import * as React from "react";
import { Search } from "lucide-react";

import { Button } from "@/shared/components/ui/button";
import { Card, CardContent } from "@/shared/components/ui/card";
import { Input } from "@/shared/components/ui/input";
import { Label } from "@/shared/components/ui/label";

export interface CustomerReportDateRange {
  from: string;
  to: string;
}

/**
 * Only the date range is exposed — the confirmed response had `group_by:
 * null` and still returned a classification breakdown, so grouping here
 * looks to be generated by the report itself rather than driven by a filter
 * value worth guessing at.
 *
 * Applied on submit, not on every keystroke, for the same reason as every
 * other report's date range: each change is a real network request.
 */
export function CustomerReportFilters({
  value,
  onApply,
  applying,
}: {
  value: CustomerReportDateRange;
  onApply: (value: CustomerReportDateRange) => void;
  applying: boolean;
}) {
  const [draft, setDraft] = React.useState(value);

  function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    onApply(draft);
  }

  return (
    <Card className="mb-5">
      <CardContent className="py-5">
        <form
          onSubmit={handleSubmit}
          className="flex flex-col gap-4 sm:flex-row sm:items-end sm:gap-3"
        >
          <div className="flex-1 space-y-1.5">
            <Label htmlFor="customer-report-from">From</Label>
            <Input
              id="customer-report-from"
              type="date"
              value={draft.from}
              max={draft.to}
              onChange={(event) => setDraft((prev) => ({ ...prev, from: event.target.value }))}
              required
            />
          </div>

          <div className="flex-1 space-y-1.5">
            <Label htmlFor="customer-report-to">To</Label>
            <Input
              id="customer-report-to"
              type="date"
              value={draft.to}
              min={draft.from}
              onChange={(event) => setDraft((prev) => ({ ...prev, to: event.target.value }))}
              required
            />
          </div>

          <Button type="submit" disabled={applying}>
            <Search className="size-4" />
            Apply
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
